#dist: trusty
language: node_js
sudo: false

node_js:
  - node
#  - lts/* # safety net; don't remove
#  - node # safety net; don't remove
before_script:
  - npm install typescript
  - npm install @types/chai
  - npm install @types/mocha

  script:
  - npm run test
  - npm run check-coverage
  - npm run codecov
