package(default_visibility=["//visibility:public"])
load("@build_bazel_rules_typescript//:defs.bzl","ts_library")

ts_library(
    name = "singly",
    srcs = ["SingleLinkedList.ts","SinglyLinkedNode.ts", "TailedSingleLinkedList.ts"],
    deps=[],
     tsconfig = "config/tsconfig.json"
)
