package(default_visibility = ["//visibility:public"])
load("@build_bazel_rules_typescript//:defs.bzl","ts_library")

ts_library(
    name = "iterative",
    srcs = [],
    deps = glob(["iterative/doubly","iterative/singly"]),
    tsconfig = "config/tsconfig.json"
)
