package(default_visibility=["//visibility:public"])
load("@build_bazel_rules_typescript//:defs.bzl","ts_library")

ts_library(
    name = "doubly",
    srcs = ["DoublyLinkedNode.ts","DoublyLinkedList.ts"],
    deps=[],
     tsconfig = "config/tsconfig.json"
)
