package(default_visibility = ["//visibility:public"])
load("@build_bazel_rules_typescript//:defs.bzl","ts_library")

ts_library(
    name = "scripts",
    srcs = [],
    deps =["//scripts/listspkg","//scripts/bag"],
    tsconfig = "config/tsconfig.json"
)
